name: ElasticBuffer
version: ${project.version}
main: org.betterbox.elasticBuffer.ElasticBuffer
api-version: '1.18'
load: STARTUP
authors: [ Grzybol ]
commands:
  eb:
    description: Reload config
    usage: /<command>
    permission: elasticbuffer.reload
permissions:
  elasticbuffer.reload:
    description: "Allows use of /eb"
    default: op
